<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="98235" started-at="2018-09-26T10:55:38Z" finished-at="2018-09-26T10:57:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="98235" started-at="2018-09-26T10:55:38Z" finished-at="2018-09-26T10:57:16Z">
      <class name="com.ey.test3po.pagelevellessthan55.UserProfilePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ey.test3po.pagelevellessthan55.UserProfilePageTest@646d64ab]" name="setUp" is-config="true" duration-ms="43836" started-at="2018-09-26T10:55:39Z" finished-at="2018-09-26T10:56:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="setUserprofile(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.ey.test3po.pagelevellessthan55.UserProfilePageTest@646d64ab]" name="setUserprofile" duration-ms="43696" started-at="2018-09-26T10:56:23Z" data-provider="getQuestionnaireTestData" finished-at="2018-09-26T10:57:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1000]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[33150]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[TC_01]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.ey.test3po.pagelevellessthan55.UserProfilePageTest.setUserprofile(UserProfilePageTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUserprofile -->
        <test-method status="PASS" signature="tearDwon()[pri:0, instance:com.ey.test3po.pagelevellessthan55.UserProfilePageTest@646d64ab]" name="tearDwon" is-config="true" duration-ms="9081" started-at="2018-09-26T10:57:07Z" finished-at="2018-09-26T10:57:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
      </class> <!-- com.ey.test3po.pagelevellessthan55.UserProfilePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
