<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IN2070121W2" name="com.ey.test3po.testcases.HomePageTest" tests="8" failures="1" timestamp="06 Jul 2018 07:38:27 GMT" time="52.906" errors="0">
  <testcase name="isOnHomePage" time="21.041" classname="com.ey.test3po.testcases.HomePageTest"/>
  <testcase name="welcomeSectionTest" time="1.815" classname="com.ey.test3po.testcases.HomePageTest"/>
  <testcase name="quickStartTest" time="0.525" classname="com.ey.test3po.testcases.HomePageTest"/>
  <testcase name="easyToUnderstandTest" time="0.539" classname="com.ey.test3po.testcases.HomePageTest"/>
  <testcase name="flexibleTest" time="0.550" classname="com.ey.test3po.testcases.HomePageTest"/>
  <testcase name="deliverResultsTest" time="0.541" classname="com.ey.test3po.testcases.HomePageTest"/>
  <testcase name="testimonialArrowTest" time="26.429" classname="com.ey.test3po.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [&quot;This app helped me over the first hurdle of actually setting up goals for my life. I greatly recommend it to every one.&quot;] but found [&quot;Good App! I use it all the Time for my investment solutions&quot;]">
      <![CDATA[java.lang.AssertionError: expected ["This app helped me over the first hurdle of actually setting up goals for my life. I greatly recommend it to every one."] but found ["Good App! I use it all the Time for my investment solutions"]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.ey.test3po.testcases.HomePageTest.testimonialArrowTest(HomePageTest.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- testimonialArrowTest -->
  <testcase name="getStartedButtonClcikTest" time="1.466" classname="com.ey.test3po.testcases.HomePageTest"/>
</testsuite> <!-- com.ey.test3po.testcases.HomePageTest -->
